from ventilation_company.standard_products import (
    RectDuct, RoundDuct, RectElbow, RoundElbow,
    MaterialType, Thickness, ProductLibrary,
    make_rect_duct, make_round_duct,
)

print("=== RectDuct 400x200x1000, t=0.7 ===")
d1 = RectDuct(name="ПП", width=400, height=200, length=1000)
print(f"metal_area (legacy): {d1.metal_area:.4f} m²")
print(f"surface_area:        {d1.surface_area:.4f} m²")
print(f"blank_area:          {d1.blank_area:.4f} m²")
print(f"material_area:       {d1.material_area:.4f} m²")
print(f"weight:              {d1.weight:.4f} kg")
print(f"unit_price:          {d1.unit_price} грн")
print()

print("=== RoundDuct Ø250x1000, t=0.7 ===")
d2 = RoundDuct(name="КП", width=250, length=1000)
print(f"metal_area (legacy): {d2.metal_area:.4f} m²")
print(f"surface_area:        {d2.surface_area:.4f} m²")
print(f"blank_area:          {d2.blank_area:.4f} m²")
print(f"material_area:       {d2.material_area:.4f} m²")
print(f"weight:              {d2.weight:.4f} kg")
print(f"unit_price:          {d2.unit_price} грн")
print()

print("=== RectElbow 400x200, 90°, R=50 ===")
e1 = RectElbow(name="Відвід", width=400, height=200, angle=90, radius=50,
               top_extension=100, bottom_extension=100)
print(f"metal_area (legacy): {e1.metal_area:.4f} m²")
print(f"surface_area:        {e1.surface_area:.4f} m²")
print(f"blank_area:          {e1.blank_area:.4f} m²")
print(f"material_area:       {e1.material_area:.4f} m²")
print(f"weight:              {e1.weight:.4f} kg")
print(f"unit_price:          {e1.unit_price} грн")
print()

print("=== RoundElbow Ø250, 90°, R=50 ===")
e2 = RoundElbow(name="Відвід", width=250, angle=90, radius=50,
                top_extension=100, bottom_extension=100)
print(f"metal_area (legacy): {e2.metal_area:.4f} m²")
print(f"surface_area:        {e2.surface_area:.4f} m²")
print(f"blank_area:          {e2.blank_area:.4f} m²")
print(f"material_area:       {e2.material_area:.4f} m²")
print(f"weight:              {e2.weight:.4f} kg")
print(f"unit_price:          {e2.unit_price} грн")
print()

print("=== Enum backward compat ===")
d3 = make_rect_duct(400, 200, 1000, thickness=Thickness.T1_0, material=MaterialType.GALVANIZED)
print(f"material: {d3.material} (type: {type(d3.material).__name__})")
print(f"thickness: {d3.thickness} (type: {type(d3.thickness).__name__})")
print(f"_material_str: {d3._material_str()}")
print(f"_thickness_float: {d3._thickness_float()}")
print()

print("=== ProductLibrary ===")
lib = ProductLibrary()
lib.add(d1)
lib.add(d2)
print(f"get_total_metal_area (legacy): {lib.get_total_metal_area():.4f} m²")
print(f"get_total_surface_area:        {lib.get_total_surface_area():.4f} m²")
print(f"get_total_blank_area:          {lib.get_total_blank_area():.4f} m²")
print(f"get_total_material_area:       {lib.get_total_material_area():.4f} m²")
print(f"get_total_weight:              {lib.get_total_weight():.4f} kg")
print(f"get_total_price:               {lib.get_total_price():.2f} грн")
